name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
env:
  node_version: lts/jod
jobs:
  dependencies-cache:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ env.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.node_version }}
    - uses: actions/cache@v4
      id: node-modules-cache
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}

    - if: steps.node-modules-cache.outputs.cache-hit != 'true'
      run: npm ci
  lint:
    needs: dependencies-cache
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ env.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.node_version }}
    - uses: actions/cache@v4
      id: node-modules-cache
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}

    - run: npm run lint
  build:
    needs: dependencies-cache
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ env.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.node_version }}
    - uses: actions/cache@v4
      id: node-modules-cache
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}

    - run: npm run build
  license:
    needs: dependencies-cache
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ env.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.node_version }}
    - uses: actions/cache@v4
      id: node-modules-cache
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}

    - run: npm run license
